// Auto-generated by `mcp__Supabase__generate_typescript_types` against the
// live project schema (supabase/migrations). Regenerate after any schema
// change instead of hand-editing.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          actor_name: string | null
          after: Json | null
          before: Json | null
          changed_at: string
          changed_fields: string[] | null
          id: number
          record_id: string
          table_name: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          actor_name?: string | null
          after?: Json | null
          before?: Json | null
          changed_at?: string
          changed_fields?: string[] | null
          id?: number
          record_id: string
          table_name: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          actor_name?: string | null
          after?: Json | null
          before?: Json | null
          changed_at?: string
          changed_fields?: string[] | null
          id?: number
          record_id?: string
          table_name?: string
        }
        Relationships: []
      }
      call_number_counters: {
        Row: {
          last_number: number
          year: number
        }
        Insert: {
          last_number?: number
          year: number
        }
        Update: {
          last_number?: number
          year?: number
        }
        Relationships: []
      }
      calls: {
        Row: {
          activity_type: string
          agency_responding: string | null
          back_entered_at: string | null
          back_entered_by: string | null
          cad_call_number: string | null
          call_number: string
          call_source: string
          call_taker_id: string | null
          call_type: string | null
          caller_location: string | null
          caller_name: string | null
          caller_phone: string | null
          case_number: string | null
          created_at: string
          created_by: string
          cross_street: string | null
          destination_facility: string | null
          dispatched_at: string | null
          dispatcher_id: string | null
          disposition: string | null
          ems_transport: string | null
          entered_into_cad: boolean
          first_enroute_at: string | null
          first_on_scene_at: string | null
          id: string
          jurisdiction: string | null
          last_cleared_at: string | null
          location_address: string | null
          location_apt: string | null
          narrative: Json
          nfirs_number: string | null
          outage_id: string
          priority: string | null
          received_at: string
          report_taken: boolean | null
          status: string
          updated_at: string
          verified_at: string | null
          verified_by: string | null
          void_reason: string | null
          voided: boolean
          voided_at: string | null
          voided_by: string | null
        }
        Insert: {
          activity_type: string
          agency_responding?: string | null
          back_entered_at?: string | null
          back_entered_by?: string | null
          cad_call_number?: string | null
          call_number?: string
          call_source: string
          call_taker_id?: string | null
          call_type?: string | null
          caller_location?: string | null
          caller_name?: string | null
          caller_phone?: string | null
          case_number?: string | null
          created_at?: string
          created_by: string
          cross_street?: string | null
          destination_facility?: string | null
          dispatched_at?: string | null
          dispatcher_id?: string | null
          disposition?: string | null
          ems_transport?: string | null
          entered_into_cad?: boolean
          first_enroute_at?: string | null
          first_on_scene_at?: string | null
          id?: string
          jurisdiction?: string | null
          last_cleared_at?: string | null
          location_address?: string | null
          location_apt?: string | null
          narrative?: Json
          nfirs_number?: string | null
          outage_id: string
          priority?: string | null
          received_at: string
          report_taken?: boolean | null
          status?: string
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
          void_reason?: string | null
          voided?: boolean
          voided_at?: string | null
          voided_by?: string | null
        }
        Update: {
          activity_type?: string
          agency_responding?: string | null
          back_entered_at?: string | null
          back_entered_by?: string | null
          cad_call_number?: string | null
          call_number?: string
          call_source?: string
          call_taker_id?: string | null
          call_type?: string | null
          caller_location?: string | null
          caller_name?: string | null
          caller_phone?: string | null
          case_number?: string | null
          created_at?: string
          created_by?: string
          cross_street?: string | null
          destination_facility?: string | null
          dispatched_at?: string | null
          dispatcher_id?: string | null
          disposition?: string | null
          ems_transport?: string | null
          entered_into_cad?: boolean
          first_enroute_at?: string | null
          first_on_scene_at?: string | null
          id?: string
          jurisdiction?: string | null
          last_cleared_at?: string | null
          location_address?: string | null
          location_apt?: string | null
          narrative?: Json
          nfirs_number?: string | null
          outage_id?: string
          priority?: string | null
          received_at?: string
          report_taken?: boolean | null
          status?: string
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
          void_reason?: string | null
          voided?: boolean
          voided_at?: string | null
          voided_by?: string | null
        }
        Relationships: []
      }
      lookups: {
        Row: {
          active: boolean
          category: string
          id: string
          sort_order: number
          value: string
        }
        Insert: {
          active?: boolean
          category: string
          id?: string
          sort_order?: number
          value: string
        }
        Update: {
          active?: boolean
          category?: string
          id?: string
          sort_order?: number
          value?: string
        }
        Relationships: []
      }
      outages: {
        Row: {
          aar_completed_at: string | null
          aar_required: boolean | null
          back_entry_completed_at: string | null
          back_entry_performed_by: string | null
          back_entry_started_at: string | null
          back_entry_verified_by: string | null
          cad_restored_at: string | null
          created_at: string
          detected_by: string
          event_number: string
          failure_detected_at: string
          failure_nature: string | null
          gaps_found: boolean | null
          id: string
          last_call_number_issued: string | null
          manual_logging_started_at: string | null
          notes: string | null
          notifications: Json
          opened_by: string
          paper_form_call_numbers: string | null
          paper_forms_used: boolean
          restoration_confirmed_by: string | null
          status: string
          systems_still_operational: string | null
        }
        Insert: {
          aar_completed_at?: string | null
          aar_required?: boolean | null
          back_entry_completed_at?: string | null
          back_entry_performed_by?: string | null
          back_entry_started_at?: string | null
          back_entry_verified_by?: string | null
          cad_restored_at?: string | null
          created_at?: string
          detected_by: string
          event_number: string
          failure_detected_at: string
          failure_nature?: string | null
          gaps_found?: boolean | null
          id?: string
          last_call_number_issued?: string | null
          manual_logging_started_at?: string | null
          notes?: string | null
          notifications?: Json
          opened_by: string
          paper_form_call_numbers?: string | null
          paper_forms_used?: boolean
          restoration_confirmed_by?: string | null
          status?: string
          systems_still_operational?: string | null
        }
        Update: {
          aar_completed_at?: string | null
          aar_required?: boolean | null
          back_entry_completed_at?: string | null
          back_entry_performed_by?: string | null
          back_entry_started_at?: string | null
          back_entry_verified_by?: string | null
          cad_restored_at?: string | null
          created_at?: string
          detected_by?: string
          event_number?: string
          failure_detected_at?: string
          failure_nature?: string | null
          gaps_found?: boolean | null
          id?: string
          last_call_number_issued?: string | null
          manual_logging_started_at?: string | null
          notes?: string | null
          notifications?: Json
          opened_by?: string
          paper_form_call_numbers?: string | null
          paper_forms_used?: boolean
          restoration_confirmed_by?: string | null
          status?: string
          systems_still_operational?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          active: boolean
          agency: string
          badge_id: string | null
          created_at: string
          full_name: string
          id: string
          role: string
        }
        Insert: {
          active?: boolean
          agency?: string
          badge_id?: string | null
          created_at?: string
          full_name: string
          id: string
          role?: string
        }
        Update: {
          active?: boolean
          agency?: string
          badge_id?: string | null
          created_at?: string
          full_name?: string
          id?: string
          role?: string
        }
        Relationships: []
      }
      unit_assignments: {
        Row: {
          at_destination_at: string | null
          call_id: string
          cleared_at: string | null
          created_at: string
          dispatched_at: string | null
          enroute_at: string | null
          id: string
          notes: string | null
          odometer_end: number | null
          odometer_start: number | null
          on_scene_at: string | null
          personnel: string | null
          transporting_at: string | null
          unit_disposition: string | null
          unit_id: string
          updated_at: string
        }
        Insert: {
          at_destination_at?: string | null
          call_id: string
          cleared_at?: string | null
          created_at?: string
          dispatched_at?: string | null
          enroute_at?: string | null
          id?: string
          notes?: string | null
          odometer_end?: number | null
          odometer_start?: number | null
          on_scene_at?: string | null
          personnel?: string | null
          transporting_at?: string | null
          unit_disposition?: string | null
          unit_id: string
          updated_at?: string
        }
        Update: {
          at_destination_at?: string | null
          call_id?: string
          cleared_at?: string | null
          created_at?: string
          dispatched_at?: string | null
          enroute_at?: string | null
          id?: string
          notes?: string | null
          odometer_end?: number | null
          odometer_start?: number | null
          on_scene_at?: string | null
          personnel?: string | null
          transporting_at?: string | null
          unit_disposition?: string | null
          unit_id?: string
          updated_at?: string
        }
        Relationships: []
      }
      units: {
        Row: {
          active: boolean
          agency: string
          id: string
          sort_order: number
          unit_type: string | null
        }
        Insert: {
          active?: boolean
          agency: string
          id: string
          sort_order?: number
          unit_type?: string | null
        }
        Update: {
          active?: boolean
          agency?: string
          id?: string
          sort_order?: number
          unit_type?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_role: { Args: Record<PropertyKey, never>; Returns: string }
      current_user_active: { Args: Record<PropertyKey, never>; Returns: boolean }
      next_call_number: { Args: { p_year: number }; Returns: string }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
